language: node_js
node_js:
  - "0.10"
install:
  - travis_retry npm install -g grunt-cli@0.1.9
  - travis_retry npm install
notifications:
  email: false
cache:
  directories:
    - node_modules
branches:
  except:
    - release
    - /^release_[0-9]+$/
